version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    # command: bash -c "chmod +x bin/start && bin/start"
    volumes:
      - .:/burrow_1
    ports:
      - "3000:3000"
    depends_on:
      - db
